### ISSUE TITLE
TypeError: result.then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by wslyhbb** [AzureAD/microsoft-authentication-library-for-js#5673]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Getting this error when calling acquireTokenSilent:
TypeError: result.then(...).catch(...).finally is not a function
    at PublicClientApplication.<anonymous>
    at step
    at Object.next
    at fulfilled
    at tryCatch
    at invokeCallback
    at publish
    at MutationObserver.flush

This is directly related to #5555. The code works fine in 2.32.2 but is broken in 2.33.0. #5555 Pull Request adds a finally block.

### Error Message

TypeError: result.then(...).catch(...).finally is not a function
    at PublicClientApplication.<anonymous>
    at step
    at Object.next
    at fulfilled
    at tryCatch
    at invokeCallback
    at publish
    at MutationObserver.flush

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "",
        authority: "https://login.microsoftonline.com/f3211d0e-125b-42c3-86db-322b19a65a22/",
        redirectUri: "",
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false
    },
    system: {
        allowRedirectInIframe: true
    }
}
```

### Relevant Code Snippets

```javascript
const authentication = {
    myMSALObj: null,
    /**
     * @return {Promise}
     */
    async initialize() {
        this.myMSALObj = new Msal.PublicClientApplication(msalConfig);
        let tokenResponse = await this.myMSALObj.handleRedirectPromise();
        if (tokenResponse !== null) {
            this.myMSALObj.setActiveAccount(tokenResponse.account);
            return true;
        } else {
            const currentAccounts = this.myMSALObj.getAllAccounts();
            if (!currentAccounts || currentAccounts.length < 1) {
                await this.myMSALObj.loginRedirect(loginRequest);
            }
        }
    },
   /**
     * @return {Promise.<String>} A promise that resolves to a token for resource access
     */
    async getToken(scopes) {
        const currentAccounts = this.myMSALObj.getAllAccounts();
        scopes.account = currentAccounts[0];
        let response = await this.myMSALObj.acquireTokenSilent(scopes)
            .catch(error => {
                console.error(error);
            });
    }
}

authentication.initialize().then(() => {
   authentication.getToken({ scopes: scopes })
});
```

### Reproduction Steps

1. Install @azure/msal-browser@2.33.0
2. Initialize PublicClientApplication
3. Call acquireTokenSilent

### Expected Behavior

No error and response is returned.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

2.32.2

### Source

External (Customer)

**Comment by sameerag** [comment]
@wslyhbb How are you importing `@azure/msal-browser`?

**Comment by wslyhbb** [comment]
Hi @sameerag,
It is imported like this:
import * as Msal from '@azure/msal-browser';

The code is bundled with Webpack.

**Comment by wslyhbb** [comment]
The issue was the project was also importing and bundling es6-promise-promise. When I remove that package 2.33.0 works.

**Comment by sameerag** [comment]
@wslyhbb Thanks for the find. I will follow up on how to make this easy for users like you.

**Comment by wslyhbb** [comment]
From what I read today, not all promise libraries support finally. A then-catch-then is the equivalent of then-catch-finally.

**Comment by sameerag** [comment]
@wslyhbb We decided we will add a note regarding `finally` support in MSAL JS. I will add the link to the FAQ once it is up.

**Comment by wslyhbb** [comment]
That is fine. I think the es6-promise was in there to support IE and IE is dead and we don't support it anymore either. For us removing the polyfil package works.

**Comment by sameerag** [comment]
Sounds good. Closing this issue.

**Comment by muhzak** [comment]
I recently started getting this error again.
