### ISSUE TITLE
Login redirect does not work with @azure/msal-browser 2.7.0

### ISSUE THREAD

**Issue by akhileshea** [AzureAD/microsoft-authentication-library-for-js#2704]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `@azure/msal-browser@2.7.0`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Description
Login redirect doenst work as expected, 

## Error Message
index.es.js:1907 Uncaught (in promise) TypeError: hashString.indexOf is not a function
    at Function.UrlString.parseHash (index.es.js:1907)
    at Function.UrlString.getDeserializedHash (index.es.js:1929)
    at Function.UrlString.hashContainsKnownProperties (index.es.js:1945)
    at PublicClientApplication.ClientApplication.getRedirectResponseHash (index.es.js:9048)
    at PublicClientApplication.<anonymous> (index.es.js:8993)
    at step (index.es.js:74)
    at Object.next (index.es.js:55)
    at index.es.js:48
    at new Promise (<anonymous>)
    at __awaiter (index.es.js:44)
    at PublicClientApplication.ClientApplication.handleRedirectResponse (index.es.js:8984)
    at PublicClientApplication.<anonymous> (index.es.js:8947)
    at step (index.es.js:74)
    at Object.next (index.es.js:55)
    at index.es.js:48
    at new Promise (<anonymous>)
    at __awaiter (index.es.js:44)
    at PublicClientApplication.ClientApplication.handleRedirectPromise (index.es.js:8940)
    at Module.<anonymous> (auth.js:62)
    at Module../src/redux/auth.js (auth.js:143)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Module.<anonymous> (GuideLinesComponent.js:75)
    at Module../src/components/MainComponent.js (MainComponent.js:108)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Module.<anonymous> (App.css?dde5:82)
    at Module../src/App.js (App.js:36)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Module.<anonymous> (index.css?bb0a:82)
    at Module../src/index.js (index.js:19)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Object.1 (weekNumber.js:64)
    at __webpack_require__ (bootstrap:851)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1

## Security
No

## Regression
 Login redirect works in msal 1.3.3 , trying to migrate to msal 2.7 to fix issues with safari 3rd party cookies blocked. 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```javascript
  const loginRequest = {
    scopes: ["openid", "profile", "User.Read"]
  };

  const authRedirectCallBack = (error, response) =>  (dispatch) =>{
    if (error) {
        console.log(error);
    } else {
        if (response.tokenType === "id_token") {
            console.log("id_token acquired at: " + new Date().toString()); 
  
        } else if (response.tokenType === "access_token") {
          console.log("access_token acquired at: " + new Date().toString());
         let  accessToken = response.accessToken;
          console.log(accessToken);
        } else {
            console.log("token type is:" + response.tokenType);
        }
    }
  }
  const myMSALObj = new Msal.PublicClientApplication(msalConfig);
  myMSALObj.handleRedirectPromise(authRedirectCallBack);

  export const login = (date)=> (dispatch) =>{
    dispatch(loginInProgress(true));
    if(myMSALObj.getAllAccounts().length === 0) {
      myMSALObj.loginRedirect(loginRequest);
    }
    else {
      myMSALObj.acquireTokenSilent(loginRequest)
      .then(response => {
      console.log(response)
      })
      .catch(err => {
        console.log(err);
      })
    }
  }
```

## Expected behavior
Id token is aquired and the application uses id token for further transactions. 

## Browsers/Environment
All browsers.

**Comment by tnorling** [comment]
@akhileshea `handleRedirectPromise` does not take in a callback as a parameter like `handleRedirectCallback` did in version 1.x. Can you instead change this to something like this?

```javascript
myMSALObj.handleRedirectPromise()
.then(response => authRedirectCallBack(null, response))
.catch(error => authRedirectCallback(error, null));
```
